### PR TITLE
docker for development

### PR DESCRIPTION
**Pull request by minjja**

### CODE REVIEW

**Comment by EricClaeys** [comment]
@minjja What do these changes do, and why are they needed?  There is no description in the PR, commits, or code.

**Comment by EricClaeys** [comment]
@minjja Hi, What do these changes do, and why are they needed? There is no description in the PR, commits, or code.

**Comment by EricClaeys** [comment]
@minjja   ?

**Comment by linuxkidd** [comment]
@EricClaeys Looking over the patches, this provides a quick means of spinning up a docker container to do development work on the `allsky-website` code.  Docker containers define an environment which includes all necessary dependencies, without polluting the main host OS, and keeps the containerized code sequestered, thus providing a security boundary.

**Comment by EricClaeys** [comment]
@minjja. Please apply your changes to the "dev" branch, otherwise they will be overwritten when we make it the next release.

**Comment by EricClaeys** [comment]
Sorry, apply changes to the "home-page-customization" branch.

**Pull request closed without merging**
